/**
 * de.yaml is the source of truth; en.yaml must carry every key de.yaml does (enforced by
 * `pnpm i18n:check`, see scripts/i18n-check.mjs) but falls back to German at runtime for
 * anything missing, rather than showing a raw key.
 *
 * exercises.<locale>.json are generated by `pnpm ingest --catalog` from curated.yaml's
 * nameDe/nameEn fields (see packages/ingest/src/generateI18n.ts) — never hand-edit them, re-run
 * ingest instead.
 */
import { createI18n } from "vue-i18n";
import { getStoredLocale } from "./stores/localeStore";
import de from "./locales/de.yaml";
import en from "./locales/en.yaml";
import exercisesDe from "./locales/exercises.de.json";
import exercisesEn from "./locales/exercises.en.json";

export const i18n = createI18n({
  legacy: false,
  locale: getStoredLocale(),
  fallbackLocale: "de",
  messages: {
    de: { ...de, ...exercisesDe },
    en: { ...en, ...exercisesEn },
  },
});

/** For translating outside components — stores, composables, lib/* — where useI18n() isn't
 *  available. Reads the *current* locale at call time, which matters for anything that renders
 *  once and is read later (e.g. lib/shareCard.ts painting text into a canvas): call this at the
 *  point of use, never cache its result. */
export const t = i18n.global.t;
