/**
 * i18n from day one (audit §2.8) — every string keyed here, zero translation effort spent yet.
 * `exercises.de.json` is generated by `pnpm ingest --catalog` from curated.yaml's nameDe field
 * (see packages/ingest/src/generateI18n.ts) — never hand-edit it, re-run ingest instead.
 */
import { createI18n } from "vue-i18n";
import de from "./locales/de.json";
import exercisesDe from "./locales/exercises.de.json";

export const i18n = createI18n({
  legacy: false,
  locale: "de",
  fallbackLocale: "de",
  messages: { de: { ...de, ...exercisesDe } },
});
